package com.menasy.merkezisagliksistemi.utils

fun toTurkishDisplayText(value: String): String {
    return value
        .replace("Cocuk", "Çocuk")
        .replace("cocuk", "çocuk")
        .replace("Sagligi", "Sağlığı")
        .replace("sagligi", "sağlığı")
        .replace("Hastaliklari", "Hastalıkları")
        .replace("hastaliklari", "hastalıkları")
        .replace("Hastaliklar", "Hastalıklar")
        .replace("hastaliklar", "hastalıklar")
        .replace("Gogus", "Göğüs")
        .replace("gogus", "göğüs")
        .replace("Goz", "Göz")
        .replace("goz", "göz")
        .replace("Bogaz", "Boğaz")
        .replace("bogaz", "boğaz")
        .replace("Uroloji", "Üroloji")
        .replace("uroloji", "üroloji")
        .replace("Noroloji", "Nöroloji")
        .replace("noroloji", "nöroloji")
        .replace("Nukleer", "Nükleer")
        .replace("nukleer", "nükleer")
        .replace("Tibbi", "Tıbbi")
        .replace("tibbi", "tıbbi")
        .replace("Dis", "Diş")
        .replace("dis", "diş")
        .replace("Kadin", "Kadın")
        .replace("kadin", "kadın")
        .replace("Dogum", "Doğum")
        .replace("dogum", "doğum")
        .replace("Ilce", "İlçe")
        .replace("ilce", "ilçe")
        .replace("Il ", "İl ")
        .replace(" il ", " il ")
}
